### ISSUE TITLE
Import with or without css

### ISSUE THREAD

**Issue by jacques-trixta** [coryhouse/ps-react#23]
Hi Cory

In the video you mentioned that because in the index file we include the external .css file and not in the component TextInputBEM file the user can import with or without the css. Could you please show how you do that?

Once again your course content is absolutely fantastic and I am using your course to help me publish my first package. https://github.com/RebelOpSys/react-query-builder-semantic . Its actually one component but still working like a charm. I just want to know how to import without the style sheet

**Comment by coryhouse** [comment]
Thanks Jacques! You can import without styles like this:

`import MyComponent from 'path/to/component/MyComponent/MyComponent'`

Note that I repeat the component name at the end so that I'm importing the component file itself instead of the index.js file (which includes the style) in the parent dir.
